"""Add bot_type and knowledge_base_status to bots table

Revision ID: 19a80bdc0d3d
Revises: 
Create Date: 2025-06-28 19:18:29.395236

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '19a80bdc0d3d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bots', sa.Column('bot_type', sa.String(length=50), nullable=True))
    op.add_column('bots', sa.Column('knowledge_base_status', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bots', 'knowledge_base_status')
    op.drop_column('bots', 'bot_type')
    # ### end Alembic commands ###
