"""Add avatar, first_name, last_name to User

Revision ID: 99d19005c0c4
Revises: f2b1e9907336
Create Date: 2025-07-22 12:33:54.049785

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '99d19005c0c4'
down_revision: Union[str, None] = 'f2b1e9907336'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('email_verifications_user_id_fkey', 'email_verifications', type_='foreignkey')
    op.create_foreign_key(None, 'email_verifications', 'users', ['user_id'], ['id'])
    op.add_column('users', sa.Column('avatar', sa.String(), nullable=True))
    op.add_column('users', sa.Column('first_name', sa.String(), nullable=True))
    op.add_column('users', sa.Column('last_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_name')
    op.drop_column('users', 'first_name')
    op.drop_column('users', 'avatar')
    op.drop_constraint(None, 'email_verifications', type_='foreignkey')
    op.create_foreign_key('email_verifications_user_id_fkey', 'email_verifications', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
