"""Add rate limiting and IP tracking

Revision ID: ddb63b4e85cb
Revises: a08b4d3d0ab0
Create Date: 2025-07-03 16:49:35.566713

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ddb63b4e85cb'
down_revision: Union[str, None] = 'a08b4d3d0ab0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rate_limits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ip_address', sa.String(), nullable=False),
    sa.Column('endpoint', sa.String(), nullable=False),
    sa.Column('request_count', sa.Integer(), nullable=True),
    sa.Column('window_start', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('last_request', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rate_limits_id'), 'rate_limits', ['id'], unique=False)
    op.create_index(op.f('ix_rate_limits_ip_address'), 'rate_limits', ['ip_address'], unique=False)
    op.add_column('pending_users', sa.Column('ip_address', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pending_users', 'ip_address')
    op.drop_index(op.f('ix_rate_limits_ip_address'), table_name='rate_limits')
    op.drop_index(op.f('ix_rate_limits_id'), table_name='rate_limits')
    op.drop_table('rate_limits')
    # ### end Alembic commands ###
