"""add_azure_storage_fields

Revision ID: fead8f0cead7
Revises: 53c96a6d06ce
Create Date: 2025-07-09 09:31:56.809085

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fead8f0cead7'
down_revision: Union[str, None] = '53c96a6d06ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('feedback_images', sa.Column('storage_type', sa.String(length=20), nullable=True))
    op.add_column('feedback_images', sa.Column('original_filename', sa.String(length=255), nullable=True))
    op.alter_column('feedback_images', 'file_id',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('feedback_images', 'file_path',
               existing_type=sa.VARCHAR(length=500),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('feedback_images', 'file_path',
               existing_type=sa.VARCHAR(length=500),
               nullable=True)
    op.alter_column('feedback_images', 'file_id',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_column('feedback_images', 'original_filename')
    op.drop_column('feedback_images', 'storage_type')
    # ### end Alembic commands ###
